SMODS.Challenge {
    key = "battleroyale",
    restrictions = {
        banned_cards = {
            -- Jokers that prevent destruction
            {id = "j_hodge_spaghettification"},
            -- Jokers that give cards or change enhancements
            {id = "j_marble"},
            {id = "j_dna"},
            {id = "j_vampire"},
            {id = "j_midas_mask"},
            {id = "j_certificate"},
            {id = "j_hodge_metamorphosis"},
            -- Consumables that change enhancements/give cards
            {id = "c_magician"},
            {id = "c_empress"},
            {id = "c_heirophant"},
            {id = "c_lovers"},
            {id = "c_chariot"},
            {id = "c_justice"},
            {id = "c_devil"},
            {id = "c_tower"},
            {id = "c_hodge_immortality"},
            {id = "c_hodge_aquakinesis"},
            {id = "c_hodge_toxigenesis"},
            {id = "c_familiar"},
            {id = "c_grim"},
            {id = "c_incantation"},
            {id = "c_cryptid"},
            -- Vouchers that give playing cards
            {id = "v_magic_trick"},
            {id = "v_illusion"},
            -- Standard packs
            {id = "p_standard_normal_1",ids={
                "p_standard_normal_2",
                "p_standard_normal_3",
                "p_standard_normal_4",
                "p_standard_jumbo_1",
                "p_standard_jumbo_2",
                "p_standard_mega_1",
                "p_standard_mega_2"
            }},
        },
        banned_tags = {
            {id = "tag_standard"}
        }
    },
    deck = {
        type = "Challenge Deck",
        cards = {
            -- Clubs
            {s = 'C', r = 'A', e = "m_hodge_blackhole"},
            {s = 'C', r = 'K', e = "m_hodge_blackhole"},
            {s = 'C', r = 'Q', e = "m_hodge_blackhole"},
            {s = 'C', r = 'J', e = "m_hodge_blackhole"},
            {s = 'C', r = 'T', e = "m_hodge_blackhole"},
            {s = 'C', r = '9', e = "m_hodge_blackhole"},
            {s = 'C', r = '8', e = "m_hodge_blackhole"},
            {s = 'C', r = '7', e = "m_hodge_blackhole"},
            {s = 'C', r = '6', e = "m_hodge_blackhole"},
            {s = 'C', r = '5', e = "m_hodge_blackhole"},
            {s = 'C', r = '4', e = "m_hodge_blackhole"},
            {s = 'C', r = '3', e = "m_hodge_blackhole"},
            {s = 'C', r = '2', e = "m_hodge_blackhole"},
            -- Diamonds
            {s = 'D', r = 'A', e = "m_hodge_blackhole"},
            {s = 'D', r = 'K', e = "m_hodge_blackhole"},
            {s = 'D', r = 'Q', e = "m_hodge_blackhole"},
            {s = 'D', r = 'J', e = "m_hodge_blackhole"},
            {s = 'D', r = 'T', e = "m_hodge_blackhole"},
            {s = 'D', r = '9', e = "m_hodge_blackhole"},
            {s = 'D', r = '8', e = "m_hodge_blackhole"},
            {s = 'D', r = '7', e = "m_hodge_blackhole"},
            {s = 'D', r = '6', e = "m_hodge_blackhole"},
            {s = 'D', r = '5', e = "m_hodge_blackhole"},
            {s = 'D', r = '4', e = "m_hodge_blackhole"},
            {s = 'D', r = '3', e = "m_hodge_blackhole"},
            {s = 'D', r = '2', e = "m_hodge_blackhole"},
            -- Hearts
            {s = 'H', r = 'A', e = "m_hodge_blackhole"},
            {s = 'H', r = 'K', e = "m_hodge_blackhole"},
            {s = 'H', r = 'Q', e = "m_hodge_blackhole"},
            {s = 'H', r = 'J', e = "m_hodge_blackhole"},
            {s = 'H', r = 'T', e = "m_hodge_blackhole"},
            {s = 'H', r = '9', e = "m_hodge_blackhole"},
            {s = 'H', r = '8', e = "m_hodge_blackhole"},
            {s = 'H', r = '7', e = "m_hodge_blackhole"},
            {s = 'H', r = '6', e = "m_hodge_blackhole"},
            {s = 'H', r = '5', e = "m_hodge_blackhole"},
            {s = 'H', r = '4', e = "m_hodge_blackhole"},
            {s = 'H', r = '3', e = "m_hodge_blackhole"},
            {s = 'H', r = '2', e = "m_hodge_blackhole"},
            -- Spades
            {s = 'S', r = 'A', e = "m_hodge_blackhole"},
            {s = 'S', r = 'K', e = "m_hodge_blackhole"},
            {s = 'S', r = 'Q', e = "m_hodge_blackhole"},
            {s = 'S', r = 'J', e = "m_hodge_blackhole"},
            {s = 'S', r = 'T', e = "m_hodge_blackhole"},
            {s = 'S', r = '9', e = "m_hodge_blackhole"},
            {s = 'S', r = '8', e = "m_hodge_blackhole"},
            {s = 'S', r = '7', e = "m_hodge_blackhole"},
            {s = 'S', r = '6', e = "m_hodge_blackhole"},
            {s = 'S', r = '5', e = "m_hodge_blackhole"},
            {s = 'S', r = '4', e = "m_hodge_blackhole"},
            {s = 'S', r = '3', e = "m_hodge_blackhole"},
            {s = 'S', r = '2', e = "m_hodge_blackhole"},
            -- Suns
            {s = 'hodge_SUNS', r = 'A', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = 'K', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = 'Q', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = 'J', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = 'T', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = '9', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = '8', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = '7', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = '6', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = '5', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = '4', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = '3', e = "m_hodge_blackhole"},
            {s = 'hodge_SUNS', r = '2', e = "m_hodge_blackhole"},
            -- Moons
            {s = 'hodge_MOONS', r = 'A', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = 'K', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = 'Q', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = 'J', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = 'T', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = '9', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = '8', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = '7', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = '6', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = '5', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = '4', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = '3', e = "m_hodge_blackhole"},
            {s = 'hodge_MOONS', r = '2', e = "m_hodge_blackhole"},
            -- Snakes
            {s = 'hodge_SNAKE', r = 'A', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = 'K', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = 'Q', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = 'J', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = 'T', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = '9', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = '8', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = '7', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = '6', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = '5', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = '4', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = '3', e = "m_hodge_blackhole"},
            {s = 'hodge_SNAKE', r = '2', e = "m_hodge_blackhole"},
            -- Ladders
            {s = 'hodge_LADDERS', r = 'A', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = 'K', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = 'Q', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = 'J', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = 'T', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = '9', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = '8', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = '7', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = '6', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = '5', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = '4', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = '3', e = "m_hodge_blackhole"},
            {s = 'hodge_LADDERS', r = '2', e = "m_hodge_blackhole"},

        }
        --enhancement = "m_hodge_blackhole"
    }
}